ci: move from drone ci to github actions
Besides the CI migration, the golangci-lint version is bumped and added
a timeout flag for execution.

Signed-off-by: Zespre Chang <zespre.chang@suse.com>

diff --git a/package/Dockerfile.webhook b/package/Dockerfile.webhook
--- a/package/Dockerfile.webhook
+++ b/package/Dockerfile.webhook
@@ -1,8 +1,19 @@
+# syntax=docker/dockerfile:1.7.0
+
 FROM registry.suse.com/bci/bci-base:15.5
 
 RUN zypper -n rm container-suseconnect && \
     zypper -n in curl
 
-COPY bin/vm-dhcp-webhook /usr/bin/vm-dhcp-webhook
+ARG TARGETPLATFORM
+
+RUN if [ "$TARGETPLATFORM" != "linux/amd64" ] && [ "$TARGETPLATFORM" != "linux/arm64" ]; then \
+    echo "Error: Unsupported TARGETPLATFORM: $TARGETPLATFORM" && \
+    exit 1; \
+    fi
+
+ENV ARCH=${TARGETPLATFORM#linux/}
+
+COPY bin/vm-dhcp-webhook-${ARCH} /usr/bin/vm-dhcp-webhook
 
 ENTRYPOINT [ "vm-dhcp-webhook" ]
